"""empty message

Revision ID: 13d2f1c13f0d
Revises: 76824af212c2
Create Date: 2019-07-01 16:58:20.798166

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13d2f1c13f0d'
down_revision = '76824af212c2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('capture_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.String(length=64), nullable=True),
    sa.Column('source_type', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('capture_logs')
    # ### end Alembic commands ###
